name: 'Close milestones that are at 100%'
description: 'Automatically closes milestones that have no more open issues/PRs ✨'
author: 'Instantish'
branding:
  icon: 'book'  
  color: 'green'
inputs:
  debug-only:
    description: 'Run the processor in debug mode without actually performing any operations on live milestones.'
    required: false
    default: 'false'
  min-issues:
    description: 'The minimum number of issues that a milestone needs to have to get closed.'
    required: false
    default: '1'
  repo-token:
    description: 'Token used to access the repository.'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
